import type { Metadata } from "next";
import "./globals.css";
import '@mantine/core/styles.css';
import { geistMono, geistSans } from "@/config/fonts";
import ThemeProvider from "@/providers/ThemeProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
